//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScholarshipHub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messege
    {
        public int id { get; set; }
        public string FromUser { get; set; }
        public string ToUser { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public byte[] Time { get; set; }
    }
}
