//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScholarshipHub.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ScholarshipHubDataContext : DbContext
    {
        public ScholarshipHubDataContext()
            : base("name=ScholarshipHubDataContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ApplicationsToOrganization> ApplicationsToOrganizations { get; set; }
        public virtual DbSet<ApplictionsToUniversity> ApplictionsToUniversities { get; set; }
        public virtual DbSet<Messege> Messeges { get; set; }
        public virtual DbSet<Organisation> Organisations { get; set; }
        public virtual DbSet<OrganizationOffer> OrganizationOffers { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<University> Universities { get; set; }
        public virtual DbSet<UniversityOffer> UniversityOffers { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
